export type Person = {
  /** Supabase auth user id — present only for real members; sample
   * personas have no id, so Coffee Chat applies to them stay demo-only. */
  userId?: string;
  initials: string;
  avatarBg: string;
  avatarText: string;
  name: string;
  age: number;
  tenure: string;
  from: string;
  fromCity: string;
  to: string;
  toCity: string;
  industry: string;
  role: string;
  companies: string;
  bio: string;
  /** Legacy review metrics — no longer rendered (kept optional for samples). */
  rating?: string;
  sessions?: number;
  badge: string;
  /** Set when this row came from SAMPLE_PEOPLE so admins can dismiss it. */
  _sampleKey?: string;
};

export const SAMPLE_PEOPLE: Person[] = [
  {
    initials: "YT",
    avatarBg: "#0055A4",
    avatarText: "#FFF6E8",
    name: "YT さん",
    age: 34,
    tenure: "在SG 3年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Tech",
    role: "プロダクトマネージャー",
    companies: "Sony → Shopee",
    bio: "日系大手から東南アジアTechへ。3年で乗り越えた話なら。",
    rating: "4.9",
    sessions: 23,
    badge: "⚡ 相談可",
  },
  {
    initials: "RN",
    avatarBg: "#FFC93C",
    avatarText: "#0A1F3D",
    name: "RN さん",
    age: 31,
    tenure: "在SG 1年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Tech",
    role: "ソフトウェアエンジニア",
    companies: "DeNA → Grab",
    bio: "エンジニアでローカル採用される現実。準備した英語と技術。",
    rating: "4.8",
    sessions: 8,
    badge: "NEW",
  },
  {
    initials: "HK",
    avatarBg: "#4ECDC4",
    avatarText: "#0A1F3D",
    name: "HK さん",
    age: 42,
    tenure: "在SGN 4年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Vietnam",
    toCity: "Ho Chi Minh",
    industry: "Startup",
    role: "法人営業",
    companies: "商社 → 個人起業",
    bio: "商社→VN起業。家族同行と現地パートナー探しの3つの基準。",
    rating: "4.9",
    sessions: 41,
    badge: "⭐ 4.9",
  },
  {
    initials: "SK",
    avatarBg: "#6B4F8E",
    avatarText: "#FFF6E8",
    name: "SK さん",
    age: 38,
    tenure: "在SG 5年目",
    from: "Japan",
    fromCity: "Osaka",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Consumer",
    role: "マーケティング・販促",
    companies: "P&G Japan → P&G APAC",
    bio: "消費財マーケで日本→APACリージョナル。社内異動の交渉術。",
    rating: "4.7",
    sessions: 15,
    badge: "⚡ 相談可",
  },
  {
    initials: "TM",
    avatarBg: "#1FA89E",
    avatarText: "#FFF6E8",
    name: "TM さん",
    age: 29,
    tenure: "在HKG 2年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Hong Kong",
    toCity: "Hong Kong",
    industry: "Finance",
    role: "経理・財務",
    companies: "日系銀行 → 外資IB",
    bio: "新卒日系→外資IB香港。語学とテクニカルどう詰めた?",
    rating: "4.8",
    sessions: 19,
    badge: "⚡ 相談可",
  },
  {
    initials: "AK",
    avatarBg: "#0A1F3D",
    avatarText: "#FFC93C",
    name: "AK さん",
    age: 36,
    tenure: "在SG 4年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Tech",
    role: "UI/UXデザイナー",
    companies: "メルカリ → Shopee",
    bio: "デザインリードとして英語環境へ。ポートフォリオの作り方。",
    rating: "4.9",
    sessions: 27,
    badge: "⭐ 4.9",
  },
  {
    initials: "MS",
    avatarBg: "#FFC93C",
    avatarText: "#0A1F3D",
    name: "MS さん",
    age: 33,
    tenure: "在BKK 2年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Thailand",
    toCity: "Bangkok",
    industry: "Startup",
    role: "法人営業",
    companies: "日系商社 → 現地スタートアップ",
    bio: "タイのSmart Visaと起業家枠の最新申請プロセス。",
    rating: "4.7",
    sessions: 12,
    badge: "⚡ 相談可",
  },
  {
    initials: "JN",
    avatarBg: "#0055A4",
    avatarText: "#FFF6E8",
    name: "JN さん",
    age: 35,
    tenure: "在SF 3年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "United States",
    toCity: "San Francisco",
    industry: "Tech",
    role: "ソフトウェアエンジニア",
    companies: "楽天 → US Tech",
    bio: "H1Bと現地転職。技術面接とビザの両立。",
    rating: "4.9",
    sessions: 34,
    badge: "⭐ 4.9",
  },
  {
    initials: "KW",
    avatarBg: "#6B4F8E",
    avatarText: "#FFF6E8",
    name: "KW さん",
    age: 40,
    tenure: "在SG 6年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Finance",
    role: "法人営業",
    companies: "日系証券 → 米系IB",
    bio: "シニア層の現地転職。家族同行と教育費。",
    rating: "4.8",
    sessions: 22,
    badge: "⚡ 相談可",
  },
  {
    initials: "NA",
    avatarBg: "#4ECDC4",
    avatarText: "#0A1F3D",
    name: "NA さん",
    age: 32,
    tenure: "在SG 2年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Tech",
    role: "駐在帯同",
    companies: "夫の駐在で帯同",
    bio: "駐在帯同で来星。EP申請、住居、子供の学校、再就職活動の現実。",
    rating: "4.9",
    sessions: 11,
    badge: "⚡ 相談可",
  },
  {
    initials: "HM",
    avatarBg: "#1FA89E",
    avatarText: "#FFF6E8",
    name: "HM さん",
    age: 30,
    tenure: "在SGN 1年目",
    from: "Japan",
    fromCity: "Osaka",
    to: "Vietnam",
    toCity: "Ho Chi Minh",
    industry: "Manufacturing",
    role: "ソフトウェアエンジニア",
    companies: "製造業 → 現地工場",
    bio: "製造業からベトナム現地法人へ。技術者の海外赴任。",
    rating: "4.6",
    sessions: 7,
    badge: "NEW",
  },
  {
    initials: "YS",
    avatarBg: "#FFC93C",
    avatarText: "#0A1F3D",
    name: "YS さん",
    age: 37,
    tenure: "在NYC 4年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "United States",
    toCity: "New York",
    industry: "Finance",
    role: "経理・財務",
    companies: "日系銀行 → US Bank",
    bio: "NYでの金融キャリア。ビザ・税制・教育まで。",
    rating: "4.9",
    sessions: 31,
    badge: "⭐ 4.9",
  },
  {
    initials: "TF",
    avatarBg: "#0055A4",
    avatarText: "#FFF6E8",
    name: "TF さん",
    age: 28,
    tenure: "在SG 1年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Startup",
    role: "ソフトウェアエンジニア",
    companies: "日系SaaS → SG Startup",
    bio: "若手エンジニアの海外Startup挑戦。",
    rating: "4.7",
    sessions: 6,
    badge: "NEW",
  },
  {
    initials: "RT",
    avatarBg: "#6B4F8E",
    avatarText: "#FFF6E8",
    name: "RT さん",
    age: 39,
    tenure: "在SG 5年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Consumer",
    role: "人事・採用",
    companies: "日系メーカー → 外資FMCG",
    bio: "HRBPとして英語環境へ。組織変革とローカルカルチャー。",
    rating: "4.8",
    sessions: 18,
    badge: "⚡ 相談可",
  },
  {
    initials: "UE",
    avatarBg: "#4ECDC4",
    avatarText: "#0A1F3D",
    name: "UE さん",
    age: 34,
    tenure: "在HKG 3年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Hong Kong",
    toCity: "Hong Kong",
    industry: "Tech",
    role: "プロダクトマネージャー",
    companies: "ヤフー → Tencent HK",
    bio: "中華圏Tech企業でPM。中国語学習と意思決定スピード。",
    rating: "4.8",
    sessions: 14,
    badge: "⚡ 相談可",
  },
  {
    initials: "KO",
    avatarBg: "#FFC93C",
    avatarText: "#0A1F3D",
    name: "KO さん",
    age: 36,
    tenure: "在London 3年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "United States",
    toCity: "New York",
    industry: "Tech",
    role: "プロダクトマネージャー",
    companies: "Sony → Spotify",
    bio: "東京→ロンドン→NY。3か国を経験したPM視点。",
    rating: "4.9",
    sessions: 25,
    badge: "⭐ 4.9",
  },
  {
    initials: "IT",
    avatarBg: "#0A1F3D",
    avatarText: "#FFC93C",
    name: "IT さん",
    age: 41,
    tenure: "在JKT 5年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Indonesia",
    toCity: "Jakarta",
    industry: "Manufacturing",
    role: "法人営業",
    companies: "商社 → インドネシア駐在 → 現地法人代表",
    bio: "ジャカルタ駐在から現地法人代表へ。生活と人脈。",
    rating: "4.8",
    sessions: 20,
    badge: "⚡ 相談可",
  },
  {
    initials: "EM",
    avatarBg: "#1FA89E",
    avatarText: "#FFF6E8",
    name: "EM さん",
    age: 33,
    tenure: "在SG 2年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Healthcare",
    role: "法人営業",
    companies: "武田 → 外資ヘルスケアAPAC",
    bio: "製薬→ヘルスケアAPAC営業。リージョナル統括の実態。",
    rating: "4.7",
    sessions: 9,
    badge: "NEW",
  },
  {
    initials: "OK",
    avatarBg: "#0055A4",
    avatarText: "#FFF6E8",
    name: "OK さん",
    age: 38,
    tenure: "在SG 4年目",
    from: "Japan",
    fromCity: "Tokyo",
    to: "Singapore",
    toCity: "Singapore",
    industry: "Tech",
    role: "マーケティング・販促",
    companies: "リクルート → Tech Unicorn",
    bio: "B2C出身のグロースマーケ。SG発APACへの展開戦略。",
    rating: "4.8",
    sessions: 16,
    badge: "⚡ 相談可",
  },
  {
    initials: "KZ",
    avatarBg: "#6B4F8E",
    avatarText: "#FFF6E8",
    name: "KZ さん",
    age: 31,
    tenure: "在KUL 2年目",
    from: "Japan",
    fromCity: "Osaka",
    to: "Malaysia",
    toCity: "Kuala Lumpur",
    industry: "Tech",
    role: "ソフトウェアエンジニア",
    companies: "日系SIer → KL Tech",
    bio: "KLでの生活コストと技術者キャリア。",
    rating: "4.6",
    sessions: 5,
    badge: "NEW",
  },
];
